export let initialCards = [
  {
    nameRU: "Архыз",
    link: "https://pictures.s3.yandex.net/frontend-developer/cards-compressed/arkhyz.jpg",
    duration: 17,
    isLiked: false,
  },
  {
    nameRU: "Челябинская область",
    link: "https://pictures.s3.yandex.net/frontend-developer/cards-compressed/chelyabinsk-oblast.jpg",
    duration: 107,
    isLiked: false,
  },
  {
    nameRU: "Иваново",
    link: "https://pictures.s3.yandex.net/frontend-developer/cards-compressed/ivanovo.jpg",
    duration: 107,
    isLiked: true,
  },
  {
    nameRU: "Камчатка",
    link: "https://pictures.s3.yandex.net/frontend-developer/cards-compressed/kamchatka.jpg",
    duration: 107,
    isLiked: false,
  },
  {
    nameRU: "Холмогорский район",
    link: "https://pictures.s3.yandex.net/frontend-developer/cards-compressed/kholmogorsky-rayon.jpg",
    duration: 29,
    isLiked: true,
  },
  {
    nameRU: "Байкал",
    link: "https://pictures.s3.yandex.net/frontend-developer/cards-compressed/baikal.jpg",
    duration: 107,
    isLiked: false,
  },
  {
    nameRU: "Архыз",
    link: "https://pictures.s3.yandex.net/frontend-developer/cards-compressed/arkhyz.jpg",
    duration: 17,
    isLiked: false,
  },
  {
    nameRU: "Челябинская область",
    link: "https://pictures.s3.yandex.net/frontend-developer/cards-compressed/chelyabinsk-oblast.jpg",
    duration: 107,
    isLiked: false,
  },
  {
    nameRU: "Иваново",
    link: "https://pictures.s3.yandex.net/frontend-developer/cards-compressed/ivanovo.jpg",
    duration: 107,
    isLiked: true,
  },
  {
    nameRU: "Камчатка",
    link: "https://pictures.s3.yandex.net/frontend-developer/cards-compressed/kamchatka.jpg",
    duration: 107,
    isLiked: false,
  },
  {
    nameRU: "Холмогорский район",
    link: "https://pictures.s3.yandex.net/frontend-developer/cards-compressed/kholmogorsky-rayon.jpg",
    duration: 29,
    isLiked: true,
  },
  {
    nameRU: "Байкал",
    link: "https://pictures.s3.yandex.net/frontend-developer/cards-compressed/baikal.jpg",
    duration: 107,
    isLiked: false,
  },
  {
    nameRU: "Архыз",
    link: "https://pictures.s3.yandex.net/frontend-developer/cards-compressed/arkhyz.jpg",
    duration: 17,
    isLiked: false,
  },
  {
    nameRU: "Челябинская область",
    link: "https://pictures.s3.yandex.net/frontend-developer/cards-compressed/chelyabinsk-oblast.jpg",
    duration: 107,
    isLiked: false,
  },
  {
    nameRU: "Иваново",
    link: "https://pictures.s3.yandex.net/frontend-developer/cards-compressed/ivanovo.jpg",
    duration: 107,
    isLiked: true,
  },
  {
    nameRU: "Камчатка",
    link: "https://pictures.s3.yandex.net/frontend-developer/cards-compressed/kamchatka.jpg",
    duration: 107,
    isLiked: false,
  },
  {
    nameRU: "Холмогорский район",
    link: "https://pictures.s3.yandex.net/frontend-developer/cards-compressed/kholmogorsky-rayon.jpg",
    duration: 29,
    isLiked: true,
  },
  {
    nameRU: "Байкал",
    link: "https://pictures.s3.yandex.net/frontend-developer/cards-compressed/baikal.jpg",
    duration: 107,
    isLiked: false,
  },
];